### ISSUE TITLE
AttributeError: 'torch._C.Value' object has no attribute 'debugName'

### ISSUE THREAD

**Issue by gudianyue** [Joyako/SphereFace-pytorch#2]
when i run python train.py, i got AttributeError: 'torch._C.Value' object has no attribute 'debugName'
and
Traceback (most recent call last):
  File "train.py", line 297, in <module>
    main()
  File "train.py", line 280, in main
    writer.add_graph(model, (input_data, ))
  File "/home/xiang/anaconda3/envs/pt1.0.1/lib/python3.6/site-packages/tensorboardX/writer.py", line 774, in add_graph
    self._get_file_writer().add_graph(graph(model, input_to_model, verbose, **kwargs))
  File "/home/xiang/anaconda3/envs/pt1.0.1/lib/python3.6/site-packages/tensorboardX/pytorch_graph.py", line 292, in graph
    list_of_nodes, node_stats = parse(graph, args)
  File "/home/xiang/anaconda3/envs/pt1.0.1/lib/python3.6/site-packages/tensorboardX/pytorch_graph.py", line 227, in parse
    if node.debugName() == 'self':
AttributeError: 'torch._C.Value' object has no attribute 'debugName'

**Comment by leven03** [comment]
Please update tensorboardX to 1.9
